### ISSUE TITLE
Hook is not triggered when poetry.lock changes

### ISSUE THREAD

**Issue by jaron-l** [Diaoul/pre-commit-hooks-poetry#2]
Perhaps I'm missing something but this is what I understand:

The purpose of the poetry-export hook is to keep the poetry.lock file in sync with requirements.txt. If that is true, then I think the trigger for this hook is misconfigured. Since the files parameter is set to requirements.txt, the hook is only triggered if the requirements.txt file is changed, but that is not what the user cares about. The user cares when poetry.lock is changed and wants requirements.txt to update to reflect those changes.

I'm not sure what the use case would be to check if requirements.txt has changed and update requirementx.txt to what poetry.lock is. Is it to just simply block changes to requirements.txt directly rather than pick up changes in poetry.lock?

**Comment by Diaoul** [comment]
You are correct. I think I run this hook regardless of the trigger with `--run-all` so I did not notice this behavior.
Please check the [initial issue](https://github.com/python-poetry/poetry/issues/2457) I created on poetry and the [a more advanced implementation PR](https://github.com/python-poetry/poetry/pull/2511).

**Comment by Diaoul** [comment]
"Fixed" with 8fff100d3ae3965375386b973a313b7aae6ad528
